apiVersion: v1
kind: Service
metadata:
  name: k8s-backend-alim-service
spec:
  selector:
    app: k8s-backend-alim
  ports:
    - port: 8080       # 클러스터 내부에서 접근할 포트
      targetPort: 8080 # 실제 Pod가 사용하는 포트